# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeopleManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeopleManager

  target 'PeopleManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
